spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.129.181.67:1521/ttlprodnidbpdb.db
    username: stitching
    password: Telecom2040
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        show_sql: false
    hibernate:
      ddl-auto: update